### PR TITLE
pingmessage: performance improvements

### PR DESCRIPTION
**Pull request by ES-Alexander**
Up to 27% faster for Ping360 on 2M baud serial connection
- updated `calculate_checksum` to use built in `sum` instead of manual loop
- added `__slots__` to `PingParser`
- updated `parse_byte` to directly call the relevant function for the current state
- added `ERROR` status code to be in line with [ping-cpp](https://github.com/bluerobotics/ping-cpp/blob/master/src/message/ping-parser.h#L44)

### CODE REVIEW

**Comment by ES-Alexander** [comment]
Helps with #101 (although Python's I/O can't really ever be completely as fast as compiled code).

**Review by patrickelectric — APPROVED** [review]
It looks ok to me, I would just recommend to break the commit in multiple commits since there is a couple of things that are changing to improve performance, but they are not totally clear.

An example of commit organization:
- Change sum algorithm to built-in function 
- Use `__slots__` declaration to improve access speed 
    - Reason, why, when and etc
- Break parser logic into a callback dictionary 
    -  Reason, why and etc
- Change comparison from `is` to `==` since...

**Review by patrickelectric — APPROVED** [review]

**Review by Williangalvani — APPROVED** [review]
looks good to me!

**Comment by patrickelectric** [comment]
:shipit: thanks for the updates!

**Pull request merged**
